### ISSUE TITLE
Make location of samtools a parameter of the workflow.

### ISSUE THREAD

**Issue by jonathancrabtree** [jmatsumura/targeted_assembly#7]
Treat the path to samtools (used in analyze_bam.py) the same way as the other external tool dependencies e.g., 
 
```
  emboss_tool:
    label: Path to install directory of EMBOSS needle/water executable (e.g. /path/to/packages/emboss/bin/[needle|water])
    type: File
  python2_exe:
    label: Location of the Python2 executable
    type: File

  HGA_exe:
    label: Location of the HGA executable
    type: File
  SB_exe:
    label: Location of the scaffold_builder executable
    type: File

  spades_install:
    label: Location of the SPAdes installation
    type: Directory
  velvet_install:
    label: Location of the Velvet installation
    type: Directory
```

**Comment by jonathancrabtree** [comment]
There's an alternative mechanism for configuring paths at install time by using `util/install.py`, which writes `conf.py` and then passes off control to `setup.py` to rewrite the CWL files. Not sure of the reason for the bifurcation but either one could potentially be used for this. Here are the arguments to `install.py`:

```
    parser = argparse.ArgumentParser(description='Install Targeted Assembly pipeline.')
    parser.add_argument('--source', '-s', type=str, required=True, help='Path to the Targeted Assembly source code.')
    parser.add_argument('--target', '-t', type=str, required=True, help='Path to the target install directory.')
    parser.add_argument('--python3', '-p', type=str, required=True, help='Path to the Python 3 executable.')
    parser.add_argument('--gsnap_bin', '-g', type=str, required=True, help='Path to the GMAP/GSNAP bin/ directory.')
    parser.add_argument('--smalt_bin', '-m', type=str, required=True, help='Path to the SMALT bin/ directory.')
    args = parser.parse_args()

```

**Comment by jonathancrabtree** [comment]
Added to `targeted_assembly.yml`, testing now.

**Comment by jonathancrabtree** [comment]
Done, note the new section in `targeted_assembly.yml`:

```
# Base location of samtools install
samtools_install:
    class: Directory
    path: /usr/local/packages/samtools-1.18
```
